@extends('layouts.app')

@section('title', 'Intimações por OAB')

@section('head')
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@400;600;700&display=swap" rel="stylesheet">
<style>
:root{--elev:#10131b;--a:#7c6bff;--a2:#22d3ee;--grad:linear-gradient(135deg,var(--a),var(--a2));--display:"Fraunces",Georgia,serif;--soft:var(--ink-soft);--faint:var(--ink-faint);--strong:rgba(255,255,255,.075);--border2:rgba(255,255,255,.18)}
.tabs{display:flex;gap:24px;border-bottom:1px solid var(--border);margin-bottom:20px}.tab{position:relative;padding:11px 4px 14px;color:var(--soft);font-weight:700}.tab:hover,.tab[aria-current=page]{color:var(--a2)}.tab[aria-current=page]:after{content:"";position:absolute;right:0;bottom:-1px;left:0;height:3px;background:var(--grad);border-radius:3px 3px 0 0}.panel{border:1px solid var(--border);border-radius:18px;background:var(--surface);box-shadow:0 18px 55px rgba(0,0,0,.16);backdrop-filter:blur(12px)}.search{padding:32px 24px 28px}.grid{display:grid;grid-template-columns:minmax(190px,1fr) minmax(220px,1fr) minmax(300px,1.25fr) auto auto;gap:26px;align-items:end}.wrap{min-width:0}.field{position:relative;min-width:0;height:52px;padding:17px 12px 7px;border:1px solid var(--border2);border-radius:10px;background:rgba(9,11,16,.42)}.field:focus-within{border-color:var(--a2);box-shadow:0 0 0 3px rgba(34,211,238,.1)}.field label{position:absolute;top:-8px;left:10px;padding:0 5px;color:var(--soft);background:#0d1017;font-size:12px}.field input,.field select{width:100%;height:26px;padding:0;color:var(--ink);border:0;outline:0;background:transparent}.field select option{color:#161922;background:#fff}.field input::placeholder{color:#6e7585}.with-clear{padding-right:38px}.clear-x{position:absolute;top:50%;right:7px;width:30px;height:30px;padding:0;transform:translateY(-50%);color:var(--soft);border:0;background:transparent;font-size:25px}.help{display:block;margin:8px 2px 0;color:var(--faint);font-size:11px}.period{display:grid;grid-template-columns:1fr 14px 1fr;align-items:center;gap:5px}.period span{color:var(--faint);text-align:center}input[type=date]::-webkit-calendar-picker-indicator{filter:invert(1);opacity:.72}
.btn{min-height:44px;padding:0 19px;display:inline-flex;align-items:center;justify-content:center;gap:8px;color:var(--ink);border:1px solid var(--border2);border-radius:999px;background:var(--strong);font-weight:700;white-space:nowrap}.btn svg{width:19px;height:19px}.btn:hover:not(:disabled){color:var(--a2);border-color:var(--a2);transform:translateY(-1px)}.primary{color:#0a0c12;border:0;background:var(--grad);box-shadow:0 8px 28px -8px rgba(124,107,255,.65)}.primary:hover:not(:disabled){color:#0a0c12}.btn:disabled{cursor:not-allowed;opacity:.45;transform:none}
.filters{margin-top:18px;overflow:hidden}.filters summary{min-height:58px;padding:0 20px;display:flex;align-items:center;gap:12px;cursor:pointer;font:600 19px var(--display);list-style:none}.filters summary::-webkit-details-marker{display:none}.filters summary:after{content:"";width:9px;height:9px;margin-left:auto;border-right:2px solid var(--a2);border-bottom:2px solid var(--a2);transform:rotate(45deg) translateY(-3px);transition:.2s}.filters[open] summary{border-bottom:1px solid var(--border)}.filters[open] summary:after{transform:rotate(225deg) translate(-2px,-2px)}.filter-hint{color:var(--faint);font:500 12px var(--body)}.filter-body{padding:25px 20px 22px}.filter-grid{display:grid;grid-template-columns:minmax(190px,1fr) minmax(220px,1fr) minmax(220px,1fr) auto auto;gap:24px;align-items:end}
#status{min-height:52px;margin-top:18px;padding:14px 17px;display:flex;align-items:center;gap:10px;color:var(--soft);border:1px solid var(--border);border-radius:10px;background:rgba(255,255,255,.025)}#status.error{color:#ff9d9d;border-color:rgba(255,157,157,.3)}#status.success{color:#86efac;border-color:rgba(134,239,172,.25)}.spinner{width:18px;height:18px;border:2px solid var(--border2);border-top-color:var(--a2);border-radius:50%;animation:spin .75s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.results{margin-top:18px;overflow:hidden}.results-head{min-height:62px;padding:12px 18px;display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--border)}.results h2{margin:0;font:600 21px var(--display)}.count{color:var(--soft);font-size:13px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:14px 12px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}th{color:var(--soft);background:rgba(255,255,255,.035);font-size:11px;text-transform:uppercase;letter-spacing:.05em}tbody tr:hover{background:rgba(124,107,255,.045)}.process{color:var(--a2);font-weight:700;white-space:nowrap}.parties{min-width:245px}.nowrap{white-space:nowrap}.actions{display:flex;gap:4px}.icon{width:35px;height:35px;padding:0;display:grid;place-items:center;color:var(--a2);border:1px solid transparent;border-radius:8px;background:transparent}.icon:hover{border-color:var(--border2);background:var(--strong)}.icon svg{width:20px;height:20px}.empty{padding:46px 20px;color:var(--faint);text-align:center}.pagination{padding:14px 18px;display:flex;justify-content:flex-end;align-items:center;gap:8px;border-top:1px solid var(--border)}.page-summary{margin-right:6px;color:var(--soft);font-size:13px}.page-btn{min-width:38px;min-height:36px;padding:0 12px}.page-number{min-width:36px;padding:0 8px}.page-number.current{color:#0a0c12;border:0;background:var(--grad)}.ellipsis{padding:0 3px;color:var(--faint)}.footnote{margin:17px 3px 0;color:var(--faint);font-size:12px}
dialog{width:min(900px,calc(100vw - 32px));height:min(760px,calc(100vh - 32px));padding:0;color:var(--ink);border:1px solid var(--border2);border-radius:18px;background:var(--elev);box-shadow:0 18px 55px rgba(0,0,0,.55)}dialog::backdrop{background:rgba(3,5,8,.78)}.modal{height:100%;display:grid;grid-template-rows:auto 1fr}.modal-head{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border)}.modal-head h2{margin:0;font:600 19px var(--display)}.modal-close{color:var(--ink);border:0;background:transparent;font-size:28px}#document-frame{width:100%;height:100%;border:0;background:#fff}
@media(max-width:1100px){.grid,.filter-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:23px 18px}.grid .period-field{grid-column:span 2}}@media(max-width:700px){.search{padding:28px 14px 20px}.grid,.filter-grid{grid-template-columns:1fr;gap:21px}.grid .period-field{grid-column:auto}.grid .btn,.filter-grid .btn{width:100%}.period-field{height:82px}.period{grid-template-columns:1fr;gap:1px}.period span,.filter-hint{display:none}.results-head{align-items:flex-start;flex-direction:column}.pagination{justify-content:center;flex-wrap:wrap}.page-summary{width:100%;margin:0;text-align:center}}
</style>
@endsection

@section('content')
<nav class="tabs" aria-label="Tipo de consulta"><div class="tab" aria-current="page">Diário da Justiça</div><a class="tab" href="{{ route('ferramentas.movimentacoes') }}">Movimentações processuais</a></nav>
<form id="search-form" class="search panel"><div class="grid">
<div class="wrap"><div class="field"><label for="process-number">Número do Processo</label><input id="process-number" inputmode="numeric" autocomplete="off" placeholder="0000000-00.0000.0.00.0000" maxlength="25"></div></div>
<div class="wrap"><div class="field with-clear"><label for="oab-number">Número da OAB</label><input id="oab-number" autocomplete="off" value="PR84908" placeholder="PR84908" maxlength="16" required><button id="clear-oab" class="clear-x" type="button" aria-label="Limpar OAB">×</button></div></div>
<div class="wrap"><div class="field period-field"><label>Período</label><div class="period"><input id="start-date" type="date" aria-label="Data inicial" required><span>–</span><input id="end-date" type="date" aria-label="Data final" required></div></div></div>
<button id="clear-search" class="btn" type="button">Limpar</button><button id="search-button" class="btn primary" type="submit"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>Buscar</button>
</div></form>
<details class="filters panel"><summary>Filtros avançados <span class="filter-hint">Clique para exibir tribunal, classe e partes</span></summary><div class="filter-body"><div class="filter-grid"><div class="field"><label for="tribunal-filter">Tribunal</label><select id="tribunal-filter"><option value="">Selecione um Tribunal</option></select></div><div class="field"><label for="class-filter">Classe do Processo</label><select id="class-filter"><option value="">Selecione uma Classe Judicial</option></select></div><div class="field"><label for="party-filter">Partes</label><input id="party-filter" autocomplete="off" placeholder="Nome da parte"></div><button id="clear-filters" class="btn" type="button">Limpar filtros</button><button id="apply-filters" class="btn primary" type="button">Filtrar</button></div></div></details>
<div id="status" class="status" role="status" aria-live="polite">Informe uma OAB ou um número de processo e clique em Buscar.</div>
<section class="results panel" aria-labelledby="results-title"><div class="results-head"><h2 id="results-title">Intimações encontradas</h2><span id="result-count" class="count">0 itens exibidos</span></div><div class="table-wrap"><table><thead><tr><th>Processo</th><th>Partes</th><th>Tipo de Comunicação</th><th>Tribunal</th><th>Classe</th><th>Data de Disponibilização</th><th>Ações</th></tr></thead><tbody id="results-body"></tbody></table><div id="empty-state" class="empty">Nenhuma consulta realizada.</div></div><nav id="pagination" class="pagination" aria-label="Paginação" hidden><span id="page-summary" class="page-summary">Página 1</span><button id="previous-page" class="btn page-btn" type="button" disabled>Anterior</button><span id="page-numbers"></span><button id="next-page" class="btn page-btn" type="button" disabled>Próxima</button></nav></section>
<p class="footnote">Consulta informativa ao Diário de Justiça Eletrônico Nacional (DJEN). Este painel não substitui a consulta aos sistemas oficiais nem a conferência dos prazos processuais.</p>
<dialog id="document-dialog"><div class="modal"><header class="modal-head"><h2 id="modal-title">Inteiro teor</h2><button id="modal-close" class="modal-close" type="button" aria-label="Fechar">×</button></header><iframe id="document-frame" sandbox="allow-popups" title="Inteiro teor da comunicação"></iframe></div></dialog>
<script>
(()=>{'use strict';
const API='https://comunicaapi.pje.jus.br/api/v1/comunicacao',SIZE=100,state={items:[],filtered:[],total:0,page:1,loading:false,searched:false},$=s=>document.querySelector(s),form=$('#search-form'),processInput=$('#process-number'),oabInput=$('#oab-number'),startDate=$('#start-date'),endDate=$('#end-date'),tribunal=$('#tribunal-filter'),processClass=$('#class-filter'),party=$('#party-filter'),status=$('#status'),tbody=$('#results-body'),empty=$('#empty-state'),count=$('#result-count'),pagination=$('#pagination'),pageSummary=$('#page-summary'),pageNumbers=$('#page-numbers'),previous=$('#previous-page'),next=$('#next-page'),dialog=$('#document-dialog'),frame=$('#document-frame');
const digits=v=>String(v||'').replace(/\D/g,''),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function dates(){const d=new Date;startDate.value=iso(new Date(d.getFullYear(),d.getMonth(),1));endDate.value=iso(d)}
function formatProcess(v){const d=digits(v).slice(0,20),c=[7,2,4,1,2,4],s=['-','.','.','.','.'];let r='',p=0;c.forEach((n,i)=>{const x=d.slice(p,p+n);if(x){if(i)r+=s[i-1];r+=x;p+=n}});return r}
function parseOab(v){const n=String(v||'').toUpperCase().replace(/[^A-Z0-9-]/g,''),a=n.match(/^([A-Z]{2})(.+)$/),b=n.match(/^(.+?)([A-Z]{2})$/);if(a&&/\d/.test(a[2]))return{uf:a[1],number:a[2]};if(b&&/\d/.test(b[1]))return{uf:b[2],number:b[1]};return{uf:'',number:n}}
function setStatus(message,type=''){status.className=`status${type?` ${type}`:''}`;status.replaceChildren();if(type==='loading'){const s=document.createElement('span');s.className='spinner';status.append(s)}status.append(document.createTextNode(message))}
function dateBr(v){if(!v)return'—';const[y,m,d]=v.slice(0,10).split('-');return`${d}/${m}/${y}`}
const processMasked=i=>i.numeroprocessocommascara||formatProcess(i.numero_processo||''),partiesText=i=>{const p=Array.isArray(i.destinatarios)?i.destinatarios.map(x=>x.nome).filter(Boolean):[];return p.length?p.join(' × '):'Não informado'};
function fillSelect(el,values,label){const current=el.value;el.replaceChildren(new Option(label,''));[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).forEach(v=>el.add(new Option(v,v)));if([...el.options].some(o=>o.value===current))el.value=current}
function filters(){fillSelect(tribunal,state.items.map(i=>i.siglaTribunal),'Selecione um Tribunal');fillSelect(processClass,state.items.map(i=>i.nomeClasse),'Selecione uma Classe Judicial')}
const icon=p=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">${p}</svg>`;
function action(label,html,fn){const b=document.createElement('button');b.type='button';b.className='icon';b.title=label;b.setAttribute('aria-label',label);b.innerHTML=html;b.addEventListener('click',fn);return b}
function openDocument(i){$('#modal-title').textContent=`Inteiro teor — ${processMasked(i)}`;const safe=String(i.texto||'<p>Conteúdo não informado.</p>').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<object[\s\S]*?<\/object>/gi,'').replace(/<embed[^>]*>/gi,'').replace(/\son\w+\s*=\s*(["']).*?\1/gi,'');frame.srcdoc=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><base target="_blank"><style>body{margin:24px;font:15px/1.55 Arial;color:#252a31}table{width:100%;border-collapse:collapse}td,th{padding:7px;border:1px solid #ddd}img{max-width:100%}</style></head><body>${safe}</body></html>`;dialog.showModal()}
function external(url){if(url&&/^https:\/\//i.test(url))window.open(url,'_blank','noopener,noreferrer')}
function sequence(current,total){if(total<=7)return Array.from({length:total},(_,i)=>i+1);const v=[...new Set([1,total,current-1,current,current+1])].filter(x=>x>=1&&x<=total).sort((a,b)=>a-b),r=[];v.forEach((x,i)=>{if(i&&x-v[i-1]>1)r.push('…');r.push(x)});return r}
function renderPagination(){const pages=Math.max(1,Math.ceil(state.total/SIZE));pagination.hidden=state.total<=SIZE;pageSummary.textContent=`Página ${state.page} de ${pages}`;previous.disabled=state.loading||state.page<=1;next.disabled=state.loading||state.page>=pages;pageNumbers.replaceChildren();sequence(state.page,pages).forEach(x=>{if(x==='…'){const e=document.createElement('span');e.className='ellipsis';e.textContent=x;pageNumbers.append(e);return}const b=document.createElement('button');b.type='button';b.className=`btn page-btn page-number${x===state.page?' current':''}`;b.textContent=x;b.setAttribute('aria-label',`Ir para a página ${x}`);if(x===state.page)b.setAttribute('aria-current','page');b.disabled=state.loading||x===state.page;b.addEventListener('click',()=>search(x));pageNumbers.append(b)})}
function render(){tbody.replaceChildren();empty.hidden=state.filtered.length>0;empty.textContent=state.searched?'Nenhuma intimação encontrada para os filtros selecionados.':'Nenhuma consulta realizada.';state.filtered.forEach(i=>{const row=document.createElement('tr'),vals=[{t:processMasked(i),c:'process'},{t:partiesText(i),c:'parties'},{t:i.tipoComunicacao||'—'},{t:i.siglaTribunal||'—',c:'nowrap'},{t:i.nomeClasse||'—'},{t:dateBr(i.data_disponibilizacao),c:'nowrap'}];vals.forEach(v=>{const td=document.createElement('td');td.textContent=v.t;if(v.c)td.className=v.c;row.append(td)});const td=document.createElement('td');td.className='actions';td.append(action('Visualizar inteiro teor',icon('<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>'),()=>openDocument(i)));if(i.hash)td.append(action('Abrir certidão',icon('<path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 13h6M9 17h6"/>'),()=>external(`${API}/${encodeURIComponent(i.hash)}/certidao`)));if(i.link)td.append(action('Abrir no tribunal',icon('<path d="M14 3h7v7M10 14 21 3"/><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/>'),()=>external(i.link)));row.append(td);tbody.append(row)});const n=state.filtered.length;count.textContent=`${n} ${n===1?'item exibido':'itens exibidos'}${state.total?` de ${state.total}`:''}`;renderPagination()}
function applyFilters(){const t=tribunal.value,c=processClass.value,p=party.value.trim().toLocaleLowerCase('pt-BR');state.filtered=state.items.filter(i=>(!t||i.siglaTribunal===t)&&(!c||i.nomeClasse===c)&&(!p||partiesText(i).toLocaleLowerCase('pt-BR').includes(p)));render();if(state.searched)setStatus(`${state.filtered.length} intimação(ões) nesta página após os filtros.`,'success')}
function validate(){const process=digits(processInput.value),oab=parseOab(oabInput.value);if(!process&&(!oab.number||!oab.uf))throw Error('Informe o processo ou a OAB com a UF, por exemplo: PR84908.');if(process&&process.length!==20)throw Error('O número do processo deve conter 20 dígitos.');if(oab.number&&!oab.uf)throw Error('Informe também a UF da OAB, por exemplo: PR84908.');if(!startDate.value||!endDate.value)throw Error('Informe as datas inicial e final.');if(startDate.value>endDate.value)throw Error('A data inicial não pode ser posterior à data final.');return{process,oab}}
async function search(page=1){if(state.loading)return;try{const{process,oab}=validate();state.loading=true;state.page=page;render();setStatus('Consultando o Diário da Justiça…','loading');$('#search-button').disabled=true;const q=new URLSearchParams({dataDisponibilizacaoInicio:startDate.value,dataDisponibilizacaoFim:endDate.value,meio:'D',pagina:String(page),itensPorPagina:String(SIZE)});if(process)q.set('numeroProcesso',process);if(oab.number){q.set('numeroOab',oab.number);q.set('ufOab',oab.uf)}const controller=new AbortController,timer=setTimeout(()=>controller.abort(),30000),response=await fetch(`${API}?${q}`,{headers:{Accept:'application/json'},signal:controller.signal});clearTimeout(timer);if(!response.ok)throw Error(`O serviço respondeu com o código ${response.status}. Tente novamente.`);const data=await response.json();if(!Array.isArray(data.items))throw Error('A resposta do serviço não possui o formato esperado.');state.items=data.items;state.filtered=data.items;state.total=Number(data.count||data.items.length);state.searched=true;filters();render();setStatus(`${state.total} intimação(ões) encontrada(s) no DJEN.`,'success');if(page>1)$('.results').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){setStatus(e.name==='AbortError'?'A consulta demorou mais de 30 segundos. Tente novamente.':e.message||'Não foi possível consultar o serviço.','error')}finally{state.loading=false;$('#search-button').disabled=false;render()}}
processInput.addEventListener('input',()=>processInput.value=formatProcess(processInput.value));oabInput.addEventListener('input',()=>oabInput.value=oabInput.value.toUpperCase().replace(/[^A-Z0-9-]/g,''));form.addEventListener('submit',e=>{e.preventDefault();search(1)});$('#clear-oab').addEventListener('click',()=>{oabInput.value='';oabInput.focus()});$('#clear-search').addEventListener('click',()=>{processInput.value='';oabInput.value='';dates();processInput.focus()});$('#apply-filters').addEventListener('click',applyFilters);party.addEventListener('keydown',e=>{if(e.key==='Enter')applyFilters()});$('#clear-filters').addEventListener('click',()=>{tribunal.value='';processClass.value='';party.value='';state.filtered=[...state.items];render();if(state.searched)setStatus(`${state.total} intimação(ões) encontrada(s) no DJEN.`,'success')});previous.addEventListener('click',()=>search(state.page-1));next.addEventListener('click',()=>search(state.page+1));$('#modal-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>frame.srcdoc='');dates();render();
})();
</script>
@endsection
